version: 0.0
os: linux 
hooks:
  BeforeInstall:
    - location: scripts/01-install-dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/02-configure-website.sh
      timeout: 60
      runas: root
