---
- name: Test ansible-vault
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/vault.yml

  tasks:

    - name: Create CommitFlow directories
      become: true
      file:
        path: "{{ item }}"
        state: directory
        owner: admin
        group: admin
        mode: "0755"
      loop:
        - /opt/commitflow
        - /opt/commitflow/postgres
        - /opt/commitflow/grafana
        - /opt/commitflow/grafana/dashboards
        - /opt/commitflow/grafana/datasources

    - name: Copy Postgres configuration
      copy:
        src: postgres/init.sql
        dest: /opt/commitflow/postgres/init.sql
        mode: "0444"

    - name: Copy Grafana dashboard configuration
      copy:
        src: grafana/dashboards/
        dest: /opt/commitflow/grafana/dashboards/
        mode: "0444"
    
    - name: Create Grafana datasource (Postgres)
      template:
        src: grafana/datasources/postgres.yml.j2
        dest: /opt/commitflow/grafana/datasources/postgres.yml
        mode: "0444"

    - name: Create Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: /opt/commitflow/docker-compose.yml
        mode: "0444"
