---
- name: Initialize first control plane
  hosts: controlplane0
  become: true

  tasks:
    - name: Extract control-plane join command
      ansible.builtin.shell: |
        kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Save worker join command
      ansible.builtin.set_fact:
        worker_join_cmd: "{{ join_command.stdout }}"

- name: Join worker nodes
  hosts: workers
  become: true
  tasks:
    - name: Join worker nodes to cluster
      ansible.builtin.shell: |
        {{ hostvars['controlplane0']['worker_join_cmd'] }}
      args:
        creates: /etc/kubernetes/kubelet.conf
