---
- name: Initialize first control plane
  hosts: controlplanes
  become: true
  vars:
    user: admin

  tasks:
    - name: Join other controlplanes
      ansible.builtin.shell: |
        kubeadm join 192.168.72.100:6221 --token onadma.1r5in15lmwaefdca \
        --discovery-token-ca-cert-hash sha256:9d57e692442f80bcc63fc2dd51a6b1012ea0b57e66f019c767df7f3281eedb74 \
        --control-plane --certificate-key 0a8a4b429959b26f762b7afd5eefae1f1fb7610e23ca5d9cd83695ab1ff2bd16
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: "/home/{{ user }}/.kube"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"

    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ user }}/.kube/config"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"

- name: Join worker nodes
  hosts: workers
  become: true

  tasks:
    - name: Join worker nodes to cluster
      ansible.builtin.shell: |
        kubeadm join 192.168.72.100:6221 --token onadma.1r5in15lmwaefdca \
          --discovery-token-ca-cert-hash sha256:9d57e692442f80bcc63fc2dd51a6b1012ea0b57e66f019c767df7f3281eedb74
      args:
        creates: /etc/kubernetes/kubelet.conf
